-- TABLA: CONNECTOR
DROP TABLE IF EXISTS CONNECTOR;

-- TABLA: CONNECTORSTATE
DROP TABLE IF EXISTS CONNECTORSTATE ;

-- TABLA: CONNECTOR_STATE
DROP TABLE IF EXISTS CONNECTOR_STATE ;

-- TABLA: CONTRACTSTATE
DROP TABLE IF EXISTS CONTRACTSTATE ;

-- TABLA: CONTRACT_STATE
DROP TABLE IF EXISTS CONTRACT_STATE ;

-- TABLA: PARTICIPANT
DROP TABLE IF EXISTS PARTICIPANT ;

-- TABLA: USER
DROP TABLE IF EXISTS USER ;

-- TABLA: USERCONTRACT
DROP TABLE IF EXISTS USERCONTRACT ;

-- TABLA: ROLE
DROP TABLE IF EXISTS ROLE ;

-- TABLA: USER_ROLE
DROP TABLE IF EXISTS USER_ROLE ;

-- TABLA: ACTIVITYLOG
DROP TABLE IF EXISTS ACTIVITYLOG ;